export enum Types {
  SET_SITE_CONFIG = 'SET_SITE_CONFIG',
  SET_CDN = 'SET_CDN',
  SET_MEM_INFO = 'SETMEMINFO',
  SET_DOWNLOAD_CONIFG = 'SET_DOWNLOAD_CONIFG',
  SET_COMMON_LIST = 'SET_COMMON_LIST',
  SET_HOSTNAME = 'SET_HOSTNAME'
}
