---
kind: pipeline
name: AllPipeline(QA)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-QA
  image: plugins/gcr
  settings:
    build_args:
    - website=all
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-landingpage
    tags:
    - latest
    - ${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: yaboGKE-QA
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-landingpage-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: yabo-landingpage-nginx-qa
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-QA

- name: auboGKE-QA
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-landingpage-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: aubo-landingpage-nginx-qa
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-QA

trigger:
  event:
  - tag
  ref:
  - refs/tags/allQA-*

---
kind: pipeline
name: AllPipeline(Beta)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Beta
  image: plugins/gcr
  settings:
    build_args:
    - website=all
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-landingpage
    tags:
    - latest
    - ${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: yaboGKE-Beta
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-landingpage-beta
      env: beta
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: yabo-landingpage-nginx-beta
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Beta

trigger:
  event:
  - tag
  ref:
  - refs/tags/allBeta-*

---
kind: pipeline
name: AllPipeline(Prod)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Prod
  image: plugins/gcr
  settings:
    build_args:
    - website=all
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-landingpage
    tags:
    - latest
    - ${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: yaboGKE-Demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-landingpage-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: yabo-landingpage-nginx-demo
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Demo

- name: yaboGKE-Prod
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-landingpage-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: yabo-landingpage-nginx-prod
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: auboGKE-Demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-landingpage-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: aubo-landingpage-nginx-demo
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Demo

- name: auboGKE-Prod
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-landingpage-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: aubo-landingpage-nginx-prod
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

trigger:
  event:
  - tag
  ref:
  - refs/tags/allProd-*

---
kind: pipeline
name: yaboLandingPipeline(yaboQA)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-QA
  image: plugins/gcr
  settings:
    build_args:
    - website=yabo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-landingpage
    tags:
    - latest
    - qa-${DRONE_COMMIT}
    - ${DRONE_TAG}

- name: deploy2GKE-QA
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-landingpage-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: yabo-landingpage-nginx-qa
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS

trigger:
  event:
  - tag
  ref:
  - refs/tags/yaboQA-*

---
kind: pipeline
name: yaboLandingPipeline(yaboBeta)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Beta
  image: plugins/gcr
  settings:
    build_args:
    - website=yabo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-landingpage
    tags:
    - latest
    - beta-${DRONE_COMMIT}
    - ${DRONE_TAG}

- name: deploy2GKE-Beta
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-landingpage-beta
      env: beta
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: yabo-landingpage-nginx-beta
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS

trigger:
  event:
  - tag
  ref:
  - refs/tags/yaboBeta-*

---
kind: pipeline
name: yaboLandingPipeline(yaboDemo)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Demo
  image: plugins/gcr
  settings:
    build_args:
    - website=yabo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-landingpage
    tags:
    - latest
    - demo-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-Demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-landingpage-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: yabo-landingpage-nginx-demo
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Demo

trigger:
  event:
  - tag
  ref:
  - refs/tags/yaboDemo-*

---
kind: pipeline
name: yaboLandingPipeline(yaboProd)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Prod
  image: plugins/gcr
  settings:
    build_args:
    - website=yabo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-landingpage
    tags:
    - latest
    - prod-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-Prod
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-landingpage-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: yabo-landingpage-nginx-prod
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

trigger:
  event:
  - tag
  ref:
  - refs/tags/yaboProd-*

---
kind: pipeline
name: yaboLandingPipeline(auboQA)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-QA
  image: plugins/gcr
  settings:
    build_args:
    - website=aubo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-landingpage
    tags:
    - latest
    - qa-${DRONE_COMMIT}
    - ${DRONE_TAG}

- name: deploy2GKE-QA
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-landingpage-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: aubo-landingpage-nginx-qa
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS

trigger:
  event:
  - tag
  ref:
  - refs/tags/auboQA-*

---
kind: pipeline
name: yaboLandingPipeline(auboDemo)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Demo
  image: plugins/gcr
  settings:
    build_args:
    - website=aubo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-landingpage
    tags:
    - latest
    - demo-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-Demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-landingpage-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: aubo-landingpage-nginx-demo
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Demo

trigger:
  event:
  - tag
  ref:
  - refs/tags/auboDemo-*

---
kind: pipeline
name: yaboLandingPipeline(auboProd)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Prod
  image: plugins/gcr
  settings:
    build_args:
    - website=aubo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-landingpage
    tags:
    - latest
    - prod-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-Prod
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-landingpage-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-landingpage:${DRONE_TAG}
      k8sNginxConfigMap: aubo-landingpage-nginx-prod
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

trigger:
  event:
  - tag
  ref:
  - refs/tags/auboProd-*

...
